name: typescript check

on: [push, pull_request]

jobs:
  build:
    name: compile check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.7.0
      - uses: actions/setup-node@v2.5.2
        with:
          node-version: 19
      - run: npm ci # install
      - run: npm run check # run typescript check
